"""Create task and product tables

Revision ID: d15f34505031
Revises: 
Create Date: 2024-02-29 22:49:58.472402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15f34505031'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_status', sa.Boolean(), nullable=False),
    sa.Column('shift_task_submission', sa.String(), nullable=False),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('squad', sa.String(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('nomenclature', sa.String(), nullable=False),
    sa.Column('code_ekn', sa.String(), nullable=False),
    sa.Column('identifier_rc', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_number', 'task_date')
    )
    op.create_table('products',
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('is_aggregated', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_number', 'task_date'], ['tasks.task_number', 'tasks.task_date'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('tasks')
    # ### end Alembic commands ###
